#!/usr/bin/env bash
#creating redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton school" > /var/www/html/index.nginx-debian.html
new_str="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n"
sed -i "$new_str" /etc/nginx/sites-available/default/ 
sudo service nginx start 
