#!/usr/bin/env bash
# set up load balancer
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.6
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
sudo service haproxy start
sudo sed -i -e "\$aENABLED=1" /etc/default/haproxy
file="/etc/haproxy/haproxy.cfg"
n_config="frontend http\n\tdefault_backend webservers\n\tbind *:80\n\nbackend
webservers\n\tserver 1112-web-01 35.227.36.214:80 check\n\tserver 1112-web-02 35.73.14.4:80 check\n\t"
sudo sed -i -e "20i $n_config" $file
sudo service haproxy restart                  
