#!/usr/bin/env bash
# script to checks a files

file=$1
if  [ -e "$file" ];then
	echo "holberton file exists"
	if [ -s "$file" ]; then
	echo "holbertonschool file is not empty"
	else
	echo "holbertonschool file is empty"
	fi
	if [ -f "$file" ]; then
	echo "holberton is a regular file"
	fi
else
	echo "holberton file does not exist"
fi
