#!/usr/bin/env bash
#changing IPs in hosts file
cp /etc/hosts ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
sed -i s/127.0.0.1\\slocalhost/127.0.0.2" "localhost/ ~/hosts.new
cp -f ~/hosts.new /etc/hosts
